# Generated by Django 2.1.7 on 2019-12-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreO', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeReparto', models.DateTimeField(auto_now=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.camion')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.objeto')),
            ],
        ),
    ]
